---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  label: title
  name: title
  config:
    required: true
- type: datetime
  label: publish date
  name: publish_date
  config:
    required: true
- type: textarea
  name: article
  label: article
  config:
    required: false
pages:
- _posts/running-from-wolves.md
- _posts/2018-10-29-not-at-all-a-little-bit-moderately-quite-a-bit-extremely.md
